name: Run Cypress Tests

on:
  workflow_dispatch: # Menjalankan secara manual
  push:
    branches:
      - main # Jalankan otomatis saat push ke branch utama

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Gunakan versi Node.js yang sesuai

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests (Headless Mode)
        run: npm test # Sesuai dengan script yang sudah kamu buat di package.json
